# to build docker-compose build
# to run docker-compose up
# to stop docker-compose down
services:
    api:
        image: vermavarun/skillathon-api
        ports:
            - "3100:3100"
    ui:
        image: vermavarun/skillathon-ui
        ports:
            - "3000:3000"
        environment:
            - REACT_APP_API_URL=http://localhost:3100